### ISSUE TITLE
draft が default で True になるような仕組み

### ISSUE THREAD

**Issue by crohas** [miyadaiku/miyadaiku#12]
現状 draft は True を明示しなければ、すべてが公開記事となります。

まだ途中の記事(スニペット)を誤って公開してしまうリスクがあります。

私としては default_draft のような値を 全体設定に記述し、その値が draft の初期値になるように設定できれば嬉しいと感じています。

以上、よろしくおねがいします。

**Comment by atsuoishimoto** [comment]
プロジェクトの `config.yml`か、`contents` ディレクトリの適当な ymlファイルを作成して、`draft: true` の行を追加すると、そのymlファイルが存在するディレクトリと子ディレクトリのファイルは、すべてドラフトとなります。

**Comment by crohas** [comment]
ありがとうございます。そんな方法があったのですね！
解決したのでクローズします。
