### ISSUE TITLE
特定のディレクトリ を watch 対象から外したい

### ISSUE THREAD

**Issue by crohas** [miyadaiku/miyadaiku#14]
watch モードで起動している場合、現状 `files/` に配置した CSSファイル等を編集したときにも ビルドが走ってしまいます。
files を対象からはずす、もしくは監視しないディレクトリを指定するオプションを作れないでしょうか？

ご検討をお願いします。

**Comment by atsuoishimoto** [comment]
files内のファイルが更新されたらoutputsにコピーする必要がありますので、監視は必要です。
オプションも普通は必要ないと思いますので、入れる予定はないです。

**Comment by crohas** [comment]
あ、確かにコピーは必要ですね。仕組みを勘違いしていました。
files/ の更新と同時に contents/ のビルドを走らなくする方法を聞きべきでした。

私の環境では別の解決方法が見つかったのでこのISSUEはこのままクローズでお願いします。
ありがとうございました。
