### ISSUE TITLE
contents/ の特定の ファイル (ディレクトリ) を ビルド 対象から外したい

### ISSUE THREAD

**Issue by crohas** [miyadaiku/miyadaiku#15]
普通は必要ないと思うんですが、技術系の記事を書こうと思うと記事ごとに環境を作ったり設定ファイルを置いたりしたくなります。

このとき、特定のファイルを除外できないと意図しないファイルが記事と判断されてビルドに失敗したり、遅くなったりしてしまいます。 (例えば `node_modules` を除外したいなど)

簡易的で良いので glob 形式でビルド対象から除外するためのpath を指定するための機能を作っていただけないでしょうか？
(#14 とは違い `outputs/` にコピーもしたくないです)

**Comment by atsuoishimoto** [comment]
ああ、ダウンロードするファイルではなく、記事の検証用プログラムなんかも一緒においておきたい、ということでしょうか

だいぶ特殊な用途だし、他にやりようもあると思いますので却下でｗ

**Comment by crohas** [comment]
@atsuoishimoto (通知が行くかわからなかったのでメンションします)
たしかに私の用途は特殊かもしれませんが、参考資料を一緒においておきたいケースはあると思います。
もし私の方でPRを作成したら取り込むか検討いただけますか？

**Comment by crohas** [comment]
わかりました。ありがとうございました。
