### ISSUE TITLE
標準プロパティのheaderの使い方

### ISSUE THREAD

**Issue by opennista1** [miyadaiku/miyadaiku#16]
標準プロパティのheaderの使い方について質問です。
標準プロパティのページには以下のように記載があります。
> header
> アーティクルのヘッダ要素のリストを取得します。リストの要素は、(ヘッダのid, ヘッダ要素名, ヘッダテキスト) のタプルとなります。

ヘッダ要素の利用に使いたいのですが
{{ no such element: miyadaiku.core.contents.ContentArgProxy object['header'] }} 
と出力されます。headerはどのように利用したらいいのでしょうか？

**Comment by atsuoishimoto** [comment]
すいません、 `header`-> `headers` の typoです 🙇 

https://github.com/pyjug/pythonjp-miyadaiku/blob/master/templates/installguide.html#L35 あたりでheaders を使用していますのでご参照ください。

**Comment by opennista1** [comment]
ありがとうございました
