### ISSUE TITLE
Tag/release the latest version (1.8.1)

### ISSUE THREAD

**Issue by tnir** [miyadaiku/miyadaiku#23]
[Tags on SCM](https://github.com/miyadaiku/miyadaiku/tags) and [Releases on GitHub](https://github.com/miyadaiku/miyadaiku/releases) show only one tag after 1.0.0.

Could the team use both `git tag` and GitHub Releases feature for the latest release? https://pypi.org/project/miyadaiku/#history

**Comment by atsuoishimoto** [comment]
It will, after I prepare Github action script.
