### ISSUE TITLE
日付を2つ使いたい

### ISSUE THREAD

**Issue by opennista1** [miyadaiku/miyadaiku#29]
ブログの公開日と更新日を設定したいです。
標準プロパティで日付を複数使えるようにしていただけないでしょうか。

**Comment by atsuoishimoto** [comment]
ドキュメントの更新が追いついていないのですが、現在の最新版では `date` と別に `updated` というプロパティを設定できます。

`updated` が未指定の場合は、`date` と同じ値となります。
