### ISSUE TITLE
Trailing slash の対応

### ISSUE THREAD

**Issue by righ** [miyadaiku/miyadaiku#5]
`index.html` で終わるファイルに対して `/ディレクトリ名/` としてアクセスできるなんらかの機能を提供して頂きたいです。私個人の需要としては個別のページのみ対応できれば構いません。

一覧ページ のリンクだけであれば テンプレート をカスタマイズし `article.path()` で生成された パス文字列 から `index.html` の文字列を削除する などのように対応できるのですが、 RSS フィードに 自動生成されたリンクから `index.html` を削除する方法がわかりません。
対応方法があれば教えていただけると助かります。

もし現状で対応方法がないのであれば、僭越ですが以下を提案させていただきます。

- 1, `config.yml` に `trailing_slash: true` がある場合、 `index.html` で終わる パス  から `index.html` を削除し、 `article.path()` や RSS フィード で利用する

  - デメリット: 特定の記事だけに適用できない

- 2, article ディレクティブ に `path` がある場合、それを `article.path()` や RSS フィード で利用する

  - デメリット: 誤ったパスを設定すると記事が見られなくなる

以上、ご検討よろしくお願いします。

**Comment by atsuoishimoto** [comment]
これ、python.jpでもほしい場合があったので、`canonical_url` というプロパティを追加しました。

例えば、`/index.rst`というファイルに

```
.. article::
   :canonical_url: /

test
-------------

```

と指定すると、`index.rst` へのリンクは、すべて `/` へのリンクとなります。

miyadaiku 0.48でリリースしていますので、お試しください。
