### ISSUE TITLE
madkdown利用時にdivが埋め込まれる

### ISSUE THREAD

**Issue by opennista1** [miyadaiku/miyadaiku#7]
windwos10 wsl上のubuntu16.04、python3.6.3で利用しています。

markdown形式で記事を書くと target を記載していなくても

`<div class="header_target" id="h__first_2emd_1"></div>`

が埋め込まれてしまいます。
またガイドに記載通り target を記述しても miyadaiku-build すると以下のようにhtmlに出力されてしまいます。

`:target:`
`<code>id_of_this_section1</code>`

このtargetの挙動をオフにすることはできないのでしょうか。

**Comment by atsuoishimoto** [comment]
markdownにかぎらず、rstでもhtmlでもヘッダ要素には目次作成用のdiv要素を作成するようになっています。

特に支障はないと思うのですが、何か問題になるでしょうか？


> :target:
> <code>id_of_this_section1</code>

すいません、ドキュメントの更新が漏れてました。正しくは

```
.. target: .. id_of_this_section1

xxxxx
```

としてください

**Comment by atsuoishimoto** [comment]
header_target ってクラス名はあれですね。。。

**Comment by opennista1** [comment]
ヘッダ要素にはdiv要素を作成するようになっていたんですね。targetを書いたときだけdiv要素が作成されると勘違いしていました。
ちなみにヘッダー要素に関してはdiv要素を作成ではなく、ヘッダ要素に直接idをつけていただくことは出来ないのでしょうか。
見栄えの問題なんですけど。div要素がいくつも作成されるのが気になってしまって。

それと、rst形式では

`.. target: id_of_this_section1`

と書くと

`<div class="header_target" id=" id_of_this_section1"></div>`

でdiv要素が作成できるのですが、やはりmarkdownだとdiv要素として出力されません。

`<p>.. target: id_of_this_section1</p>`

と出力されてしまいます。

**Comment by atsuoishimoto** [comment]
特に実害がないのであれば、修正するのは面倒ですね。。。

mdでもその形式でアンカーが作成されるはずなんですが。。。

https://github.com/miyadaiku/miyadaiku/blob/master/test/test_md.py#L74

お手数ですが、うまくいかないマークダウンファイルをいただけないでしょうか

**Comment by opennista1** [comment]
> 特に実害がないのであれば、修正するのは面倒ですね。。。

そうですよね。すみません。

targetの件は、添付のURLを拝見いたしました。
コロン2つで無事に出力できました。

`.. target:: id_of_this_section1`

お手数おかけしました。ありがとうございます。

**Comment by atsuoishimoto** [comment]
ご報告ありがとうございます。

ってか、 reSTで  .. target: id_of_this_section1 が通りますね。。。これ、ほんとはエラーにならないと行けないんじゃないかと思うんですが。。。http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#directives
